# Generated by Django 4.2.6 on 2024-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='movies',
            field=models.ManyToManyField(through='movie.CartItem', to='movie.movie'),
        ),
    ]
