# Generated by Django 4.2.6 on 2024-05-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_userprofile_purchasehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie1_similarities', to='movie.movie')),
                ('movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie2_similarities', to='movie.movie')),
            ],
        ),
    ]
